### ISSUE TITLE
problem with the product

### ISSUE THREAD

**Issue by Dogxll** [J2Store4/j2store4#55]
Good afternoon, I understand that you are updating your product, but why is your support team silent? You have not responded to any of my letters. I bought an image popup - your documentation states that it is suitable for J2store 3. However, it is possible to download only one version and it is for version 4. I don't have the option to upgrade to version 4 right now. How do I get image popup for version 3 (3.3.20) for joomla 3

My  purchase receipt ID: 675a0e3e23c3fc8188e10699e74398e5

you documentation

Image Popup
This app allows customer to view the product images (main image and additional image) in popup. The following features are possible with this app
Download the product image
Share and tweet in social media
Zoom in / Zoom out
Slideshow image
Requirements
**PHP version 5.4 or higher
Joomla version 3.x
J2Store 3.2.15 or higher**

**Comment by mgopin3** [comment]
I understand your concern. 
I would like to inform you that we have already issued a refund for your Image Popup—3 sites purchase, totalling $49.00. We also responded to the ticket you raised on the date specified.

In this case, I suggest you kindly check the details provided in the ticket for further information:
[[Ticket Link](https://j2store.freshdesk.com/a/tickets/36627)]

We appreciate your understanding.

**Comment by Dogxll** [comment]
Thank you for your answer, yes I received an answer by mail. I don't need a refund. I need version 3. I am ready to pay for this permit a second time. I didn't ask for a refund, I asked for help. And of course, in anticipation of an answer, I wrote wherever possible, since there was no answer by mail, apparently I was in a hurry and did not wait the necessary time. Please help me, I really hope that you still have the version for j2store 3.

**Comment by mgopin3** [comment]
@Dogxll A refund has already been processed back to your account. Currently, support for extensions in J2Store version 3 is unavailable, and unfortunately, we cannot provide assistance or development for J2Store 3. However, we are actively engaged in migrating these extensions to ensure seamless compatibility with Joomla 4 and J2Store 4. We appreciate your understanding of the challenges we are currently encountering.

**Comment by mgopin3** [comment]
@Dogxll We believe the reported issue has been addressed. Could you please confirm that the problem is resolved on your end? If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Comment by Dogxll** [comment]
You take a very long time to respond through all channels. The money was returned, but the issue remained unresolved. You just abandoned people who are on version 3. Yes, you have prepared your product for the transition, while leaving people without all the necessary programs for more than half a year. In addition to your product, there are other components on the site. It took us 8 months to write the integration of your store with our program. I don’t know how long it will take to write a new integration. At the same time, you simply left me without a choice. Do you think the problem has been solved? I don’t believe that your company has a problem with data storage. Why do I have products written in 2001, but you are not able to provide a 2019 product? Each country has its own services and solutions, the simplest thing is to create a yml catalog for Yandex. I can share with you the file that creates product unloading. It will be very great if you consider and add such an opportunity to the product for Yandex and Google

**Comment by mgopin3** [comment]
@Dogxll We would like to inform you that we have introduced our J2Store 4.x.x version as a free offering. As a result, we are unable to accommodate custom development requests at this time. However, we are fully committed to migrating all plugin compatibilities for Joomla 4 with J2Store4.

If you encounter any issues with our plugins, we will provide support exclusively for those plugins. Therefore, please rest assured that we will take note of your requirement for future consideration. We plan to incorporate this feature and release it in an upcoming J2Store 4.x release.

**Comment by Dogxll** [comment]
Good afternoon, how soon will the import/export application be implemented?18:32, 22 марта 2024 г., Gopi ***@***.***>:
@Dogxll We would like to inform you that we have introduced our J2Store 4.x.x version as a free offering. As a result, we are unable to accommodate custom development requests at this time. However, we are fully committed to migrating all plugin compatibilities for Joomla 4 with J2Store4.
If you encounter any issues with our plugins, we will provide support exclusively for those plugins. Therefore, please rest assured that we will take note of your requirement for future consideration. We plan to incorporate this feature and release it in an upcoming J2Store 4.x release.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты

**Comment by mgopin3** [comment]
@Dogxll 
I understand your concern. We would like to inform you that the Simple CSV import/export app is currently not available for J2Store 4. We are in the process of migrating compatibility for J2Store 4 with Joomla 4. Please rest assured that we have taken note of this issue and have assigned it high priority. We are actively working on migrating and releasing the import/export app compatibility for J2Store 4 as soon as possible.

**Comment by Dogxll** [comment]
Good afternoon, I'm having difficulties again. I bought easychek. By going through the available downloads and downloading the file, instead of Easy Checkout I get MOD_J2STORE_SEARCH. Please check the links in Access Old Ticket System & Old Extensions.

**Comment by mgopin3** [comment]
@Dogxll Should you encounter any issues with the purchased Easy Checkout plugin, please allow me to briefly explain the procedure. If there are any concerns or technical difficulties, you can raise a support ticket by utilizing the email address associated with your purchase. Kindly use support@j2store.org for this purpose. This email will ensure efficient resolution and prompt assistance with any inquiries or challenges you may encounter. Thank you for your cooperation.
