### ISSUE TITLE
Paypal Rest / Plus / Checkout

### ISSUE THREAD

**Issue by greifbar** [J2Store4/j2store4#76]
Hello,

there used to be a number of Paypal interfaces for J2Store. 
I have always used the Paypal REST interface from you. However, this no longer seems to be compatible with J2Store 4. I think this should be relatively easy to migrate. Is there already a plan here?
The "normal" PayPal is actually not enough for me, because I would like to offer several payment methods via PayPal (e.g. direct debit).
Are you planning to do this soon? Is there a possibility, as in the past, that you develop this and we pay for the development?

Thx
Daniel

Translated with DeepL.com (free version)

**Comment by mgopin3** [comment]
We appreciate your concern.
We would like to inform you that we have recently migrated and released compatibility updates for several payment plugins in J2Store4. In light of this, we recommend checking the latest released plugins to determine if they meet your requirements. Rest assured, we have taken note of your specific needs, and we plan to consider and migrate the mentioned plugin in a future upcoming release. Thank you for your understanding.

**Comment by mgopin3** [comment]
@greifbar We believe the reported issue has been addressed. Could you please confirm that the problem is resolved on your end? If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Comment by greifbar** [comment]
hey @mgopin3,

Thank you for your message.

No, I haven't really solved the issue yet. The normal PayPal integration can only use the standard PayPal. I'm still missing PayPal Checkout in J2Store. I think that would be very interesting, especially in the German market.

Thx

**Comment by mgopin3** [comment]
@greifbar We understand your concern and would like to inform you that currently, we offer a standard PayPal plugin as an inbuilt feature in J2Store 4, completely free of cost. Therefore, if you wish to utilize our PayPal plugin on J2Store 4, you can do so without any worries. Rest assured, we have duly noted your requirement, and we will thoroughly consider the possibilities for migration and inclusion in the upcoming release. We appreciate your understanding and patience in this matter.

**Comment by mgopin3** [comment]
@greifbar We believe the reported issue has been addressed. Could you please confirm that the problem is resolved on your end? If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!
