### ISSUE TITLE
Where is the J2Store EmailBasket repository?

### ISSUE THREAD

**Issue by krishunt** [J2Store4/j2store4#90]
J2Store support said they fixed a bug in the EmailBasket app plugin and gave me this link to download it, but the link takes me to a 404 page. https://github.com/j2store/app_emailbasket/pull/9

It has been many days, and they have not responded to my request for a new link. Can anyone help?

**Comment by mgopin3** [comment]
@krishunt Apologies for the inconvenience caused by the broken URL link. We've recently transitioned the Email-basket repository to a private repository, which may be why you encountered the 404 page. Not to worry though, as we've already addressed the issue individually on your site since you raised the ticket [[Ticket link](https://j2store.freshdesk.com/a/tickets/36900)]. Please check your **Email-basket** functionality on your site now. Additionally, we are working on fixing this issue globally and will release a new version on J2Store 4 as soon as possible. Thank you for your patience.

**Comment by mgopin3** [comment]
@krishunt We believe the reported issue has been addressed. Could you please confirm that the problem is resolved on your end? If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Comment by krishunt** [comment]
No, it is not resolved. I'm not sure why you think it would be. Here is a video of the Send button not working: https://youtu.be/-oviky_25TY

 

From: Gopi ***@***.***>
Reply-To: J2Store4/j2store4 ***@***.***>
Date: Friday, March 22, 2024 at 6:59 AM
To: J2Store4/j2store4 ***@***.***>
Cc: Kris Hunt ***@***.***>, Mention ***@***.***>
Subject: Re: [J2Store4/j2store4] Where is the J2Store EmailBasket repository? (Issue #90)

 

@krishunt We believe the reported issue has been addressed. Could you please confirm that the problem is resolved on your end? If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Comment by mgopin3** [comment]
@krishunt We have successfully resolved the issue on your site using the provided admin and FTP details. The necessary code changes have been implemented to ensure that emails are sent without any issues. Kindly verify the functionality on your site, and if you encounter any further issues, please do not hesitate to inform us. For your convenience, you can refer to this instructional video:  [[video](https://www.awesomescreenshot.com/video/26059330?key=1b2217c9c1fabfa0b8f1cbc5cf72c766)].

**Comment by krishunt** [comment]
Thank you very much. May I know how you fixed it, so I can fix it if I need to reinstall J2Store?

 

Kris

 

From: Gopi ***@***.***>
Reply-To: J2Store4/j2store4 ***@***.***>
Date: Monday, March 25, 2024 at 6:16 AM
To: J2Store4/j2store4 ***@***.***>
Cc: Kris Hunt ***@***.***>, Mention ***@***.***>
Subject: Re: [J2Store4/j2store4] Where is the J2Store EmailBasket repository? (Issue #90)

 

We have successfully resolved the issue on your site using the provided admin and FTP details. Now, the code changes will take effect on your site, and emails will be sent without any further issues. For your reference, please review this instructional video: [video].

**Comment by mgopin3** [comment]
@krishunt I kindly suggest reviewing our previous correspondence regarding this ticket [[Ticket link](https://j2store.freshdesk.com/a/tickets/36900)], where we have documented the code changes implemented on your site. Your attention to this matter is greatly appreciated. Thank you for your understanding.

**Comment by krishunt** [comment]
You are mistaken; you documented the code changes to mail_custom_modal.php, but I am no longer using the custom modal since I got the Bootstrap issue worked out. I see now that you have updated the mail.php file on 3/22/24 and you did not tell me about that.

 

From: Gopi ***@***.***>
Reply-To: J2Store4/j2store4 ***@***.***>
Date: Monday, March 25, 2024 at 8:20 AM
To: J2Store4/j2store4 ***@***.***>
Cc: Kris Hunt ***@***.***>, Mention ***@***.***>
Subject: Re: [J2Store4/j2store4] Where is the J2Store EmailBasket repository? (Issue #90)

 

@krishunt I kindly suggest reviewing our previous correspondence regarding this ticket [Ticket link], where we have documented the code changes implemented on your site. Your attention to this matter is greatly appreciated. Thank you for your understanding.

**Comment by mgopin3** [comment]
@krishunt We would like to inform you that we have addressed the issue comprehensively across both your custom modal and Bootstrap modal. Merely fixing the issue in a single modal file wouldn't constitute a thorough resolution for your website. If we were to overlook the fix in one model, it might lead to the persistence of the issue, especially if you decide to switch back to the custom modal from the Bootstrap model. Therefore, we have ensured that the fix is implemented across both models to maintain consistency and prevent any potential recurrence. We appreciate your understanding in this matter.

**Comment by mgopin3** [comment]
@krishunt We believe the reported issue has been addressed. Could you please confirm that the problem is resolved on your end? If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Comment by krishunt** [comment]
While the button now works, emails are not being sent. The message appears that says the email is sent, but the email is not actually sent. In fact, if you go to the J2Store configuration page and click the Test Email button, you get the same result. Clicking the Test Email button shows a message that the email was successfully sent, but the email never arrives. I have tried it with multiple email addresses. Because this is on the back end of Joomla, is it not a template issue. You can log in to my account and test the email button with your own email address to verify that the email never arrives.

 

 

From: Gopi ***@***.***>
Reply-To: J2Store4/j2store4 ***@***.***>
Date: Wednesday, March 27, 2024 at 11:58 PM
To: J2Store4/j2store4 ***@***.***>
Cc: Kris Hunt ***@***.***>, Mention ***@***.***>
Subject: Re: [J2Store4/j2store4] Where is the J2Store EmailBasket repository? (Issue #90)

 

@krishunt We believe the reported issue has been addressed. Could you please confirm that the problem is resolved on your end? If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Comment by mgopin3** [comment]
@krishunt This issue may arise if you are using the same email address for both the '**From**' email and the **Admin** email. It's essential to ensure that the Store administrator email is different from the From email set in the global configuration. Many email servers and clients are likely to flag an email as spam if both the '**From**' email and the **admin** email are identical. Using two distinct email addresses resolves this problem.

For example, if your From email address is [myemail1@gmail.com](mailto:myemail1@gmail.com) , then your Admin email could be [someothermail@gmail.com](mailto:someothermail@gmail.com) . If you are still encountering the same issue, please provide a superuser account details so that we can access all the restricted files on your site.

**Comment by krishunt** [comment]
The Global Configuration address and the Store Administrator address are already different. I can send a Test Email successfully from Global Configuration, but not from the J2Store/Configuration/Store page.
<img width="669" alt="system-test-email" src="https://github.com/J2Store4/j2store4/assets/5502749/91bb81b3-60d9-4452-8a25-6a667b54dfc4">
<img width="939" alt="j2store-test-email" src="https://github.com/J2Store4/j2store4/assets/5502749/8f1f09e5-71f3-4dcc-b10a-abe69ccb1059">
I have tried multiple different email addresses on the J2Store/Configuration/Store page, and none of them receive the test email.
 
I would greatly appreciate it if you could log in with superuser credentials and check it out, but I don't want to post such credentials publicly.

**Comment by mgopin3** [comment]
@krishunt We have checked and confirmed that the test email functionality for our J2Store store configuration is working without any issues. For your reference, please view this video: [[Video](https://www.awesomescreenshot.com/video/26308829?key=08459e1e9b7d2b7d77cdee08cd58da89)]. Therefore, we suggest that you check the global configuration of the mail server on your site.

**Comment by krishunt** [comment]
I can send a Test Email successfully from Global Configuration, but not from the J2Store/Configuration/Store page. Let me know how I can send superuser credentials to you privately so you can see that it is not working for me.

**Comment by mgopin3** [comment]
@krishunt You can share your Superuser credentials through this ticket [[Ticket link](https://j2store.freshdesk.com/a/tickets/36900)]. This will enable us to review the restricted global configuration settings on your site.

**Comment by afmind** [comment]
Hello,

i updated my company website to Joomla 4 and PHP 8.1, the j2store component is working the only problem is with the 
Email Basket Plugin, I try it by the website but i can't renew my download from 2019, can you send me the plugin updated to work with Joomla 4 and PHP 8.1 or 2?

thank you
